=== Aliing/WindManager/src/xml/cli_config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xsd:complexType name="constraint-type">
		<xsd:sequence>
			<xsd:element name="platform" type="xsd:string" minOccurs="0"/>
			<xsd:element name="type" type="xsd:string" minOccurs="0"/>
			<xsd:element name="version" type="xsd:string" minOccurs="0"/>
			<xsd:element name="expression" type="xsd:string" minOccurs="0"/>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string"/>
		<xsd:attribute name="name-ref" type="xsd:string"/>
	</xsd:complexType>
	<xsd:complexType name="default-value-type">
		<xsd:sequence>
			<xsd:element name="constraints" type="constraint-type" minOccurs="0"/>
		</xsd:sequence>
		<xsd:attribute name="value" type="xsd:string" use="required"/>
		<xsd:attribute name="dependence" type="xsd:string"/>
	</xsd:complexType>
	<xsd:complexType name="group-post-process-type">
		<xsd:attribute name="class"/>
		<xsd:attribute name="method"/>
	</xsd:complexType>
	<xsd:complexType name="cli-gen-type">
		<xsd:sequence>
			<xsd:element name="constraints" type="constraint-type" minOccurs="0"/>
			<xsd:element name="cmd" type="xsd:string"/>
			<xsd:element name="cli-default" type="default-value-type" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="key" type="xsd:string" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="cli-parse-type">
		<xsd:sequence>
			<xsd:element name="constraints" type="constraint-type" minOccurs="0"/>
			<xsd:element name="cmd" type="xsd:string"/>
			<xsd:element name="xml" type="xsd:string" minOccurs="0"/>
			<xsd:element name="group-post-process" type="group-post-process-type" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="param-type" mixed="true">
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="device_property" type="xsd:string"/>
	</xsd:complexType>
	<xsd:complexType name="params-type">
		<xsd:sequence>
			<xsd:element name="param" type="param-type" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="constraints" type="constraint-type" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:element name="clis">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="params" type="params-type" minOccurs="0"/>
				<xsd:element name="cli-gen" type="cli-gen-type" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element name="cli-parse" type="cli-parse-type" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== Aliing/WindManager/webapps/schema/cli_config/cli_gen/radio.xml
<?xml version="1.0" encoding="UTF-8"?>
<clis xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../../../src/xml/cli_config.xsd">
	
	<cli-gen key="radio.profile.channel_width.old">
		<constraints>
			<expression>!(${cons_channel_width_new})</expression>
		</constraints>
		<cmd><![CDATA[ radio profile <string> channel-width {1:20|2:40-above|3:40-below} ]]></cmd>
		<cli-default value="{*, 1}"/>
	</cli-gen>
	
	<cli-gen key="radio.profile.channel_width.new">
		<constraints name="cons_channel_width_new">
			<expression><![CDATA[ :p = ${platforms_all_11ac} || :v >= ${Guadalupe} ]]></expression>
		</constraints>
		<cmd><![CDATA[ radio profile <string> channel-width {1:20|5:40|4:80} ]]></cmd>
		<cli-default value="{*, 1}"/>
	</cli-gen>
	
	<cli-gen key="radio.profile.primary-channel-offset">
		<constraints name-ref="cons_channel_width_new"/>
		<cmd><![CDATA[ radio profile <string> primary-channel-offset {auto|0|1|2|3} ]]></cmd>
		<cli-default value="{*, auto}"/>
	</cli-gen>
</clis>

=== Aliing/WindManager/webapps/schema/cli_config/cli_gen/designated-server.xml
<?xml version="1.0" encoding="UTF-8"?>
<clis xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../../../src/xml/cli_config.xsd">

	<cli-gen key="designated-server.idm-proxy.dynamic">
		<constraints>
			<expression><![CDATA[ :v>=5.1.3.0 && :v<6.2.1.0  ]]></expression>
		</constraints>
		<cmd><![CDATA[ {false:no|true:} designated-server idm-proxy dynamic ]]></cmd>
		<cli-default value="{false}"/>
	</cli-gen>
	
	<cli-gen key="designated-server.idm-proxy.announce">
		<constraints>
			<version><![CDATA[ >=5.1.3.0 ]]></version>
		</constraints>
		<cmd><![CDATA[ {false:no|true:} designated-server idm-proxy announce ]]></cmd>
		<cli-default value="{false}"/>
	</cli-gen>
</clis>

=== Aliing/WindManager/webapps/schema/cli_config/cli_gen/qos.xml
<?xml version="1.0" encoding="UTF-8"?>
<clis xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../../../src/xml/cli_config.xsd">
	
	<cli-gen key="qos.classifier-map.service">
		<!-- Original CLI: qos classifier-map service <string> [ qos <number> ] [ action {permit|deny|log} ] -->
		<constraints>
			<platform><![CDATA[!= ${platforms_all_switch} && != ${platforms_all_cvg}]]></platform>
		</constraints>
		<cmd><![CDATA[ qos classifier-map service <string> qos <number> action {1:permit|2:deny} ]]></cmd>
		<cli-default value="{ftp-data, 0, 1}" dependence="{ftp-data, *, *}"/>
		<cli-default value="{tftp, 3, 1}" dependence="{tftp, *, *}"/>
		<cli-default value="{dhcp-client, 5, 1}" dependence="{dhcp-client, *, *}"/>
		<cli-default value="{dhcp-server, 5, 1}" dependence="{dhcp-server, *, *}"/>
		<cli-default value="{dns, 5, 1}" dependence="{dns, *, *}"/>
		<cli-default value="{ica, 5, 1}" dependence="{ica, *, *}"/>
		<cli-default value="{radius, 5, 1}" dependence="{radius, *, *}"/>
		<cli-default value="{radius-acct, 5, 1}" dependence="{radius-acct, *, *}"/>
		<cli-default value="{pcoip-control, 5, 1}" dependence="{pcoip-control, *, *}"/>
		<cli-default value="{pcoip-media, 5, 1}" dependence="{pcoip-media, *, *}"/>
		<cli-default value="{vocera-control, 5, 1}" dependence="{vocera-control, *, *}"/>
		<cli-default value="{vocera-media, 6, 1}" dependence="{vocera-media, *, *}"/>
		<cli-default value="{voip-svp, 6, 1}" dependence="{voip-svp, *, *}"/>
		<cli-default value="{sip, 6, 1}" dependence="{sip, *, *}"/>
		<cli-default value="{*, 2, 1}"/>
	</cli-gen>
	
	<cli-gen key="qos.classifier-map.service.log">
		<!-- Original CLI: qos classifier-map service <string> [ qos <number> ] [ action {permit|deny|log} ] -->
		<constraints>
			<platform><![CDATA[!= ${platforms_all_switch} && != ${platforms_all_cvg}]]></platform>
		</constraints>
		<cmd><![CDATA[ qos classifier-map service <string> qos <number> action log ]]></cmd>
	</cli-gen>
	
</clis>

=== Aliing/WindManager/webapps/schema/cli_config/constraints.xml
<?xml version="1.0" encoding="UTF-8"?>
<clis xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../../src/xml/cli_config.xsd">
	<params>
		<!-- 
			:p		hiveAp.getHiveApModel
			:t		hiveAp.getDeviceType
			:v		hiveAp.getSoftVer
		 -->
		 
		<param name="AP28">0</param>
		<param name="AP20">1</param>
		<param name="AP320">2</param>
		<param name="AP340">3</param>
		<param name="AP380">4</param>
		<param name="AP120">5</param>
		<param name="AP110">6</param>
		<param name="AP330">8</param>
		<param name="AP350">9</param>
		<param name="cvg">10</param>
		<param name="BR100">11</param>
		<param name="AP170">12</param>
		<param name="BR200">13</param>
		<param name="BR200wp">14</param>
		<param name="AP121">15</param>
		<param name="AP141">16</param>
		<param name="SR2024">17</param>
		<param name="BR200_LTE">19</param>
		<param name="AP370">20</param>
		<param name="AP390">21</param>
		<param name="SR2124P">22</param>
		<param name="SR2148P">23</param>
		<param name="SR2024P">24</param>
		<param name="AP230">25</param>
		<param name="VPN_Gateway">26</param>
		
		<param name="platforms_all_switch" device_property="default_device_type = Switch"/>
		<param name="platforms_all_cvg" device_property="default_device_type = VPN"/>
		<param name="platforms_support_L7_service" device_property="spt_L7_service = true"/>
		<param name="platforms_support_social_login" device_property="spt_social_login = true"/>
		<param name="platforms_all_11ac" device_property="spt_11ac = true"/>

		<param name="ap">0</param>
		<param name="br">1</param>
		<param name="vpn">2</param>
		<param name="switch">4</param>
		<param name="br+vpn">1|2</param>
		<param name="ap+switch">0|4</param>

		<param name="3.5.1.0-"><![CDATA[ <3.5.1.0 ]]></param>
		<param name="3.5.1.0=+"><![CDATA[ >=3.5.1.0 ]]></param>
		<param name="fuji">6.1.1.0</param>
		<param name="Gotham">6.1.4.0</param>
		<param name="Guadalupe">6.1.6.0</param>

		<constraints name="spt_L7_service">
			<platform>platforms_support_L7_service</platform>
			<version><![CDATA[ >= 6.0.1.0 ]]></version>
		</constraints>
		
		<!-- <constraints name="all-switch-platform" expression=":p = ${platforms_all_switch}"/> -->
		<constraints name="all-switch-platform">
			<platform>${platforms_all_switch}</platform>
		</constraints>
		
		<constraints name="spt_cloud_cwp">
			<platform>platforms_support_social_login</platform>
			<version><![CDATA[ >= ${Guadalupe} ]]></version>
		</constraints>
		
		<constraints name="not_switch">
			<expression>:p != ${platforms_all_switch}</expression>
		</constraints>
		
		<constraints name="not_cvg">
			<expression>:p != ${platforms_all_cvg}</expression>
		</constraints>
	</params>
</clis>
